if(ENABLE_ACCESSIBILITY)
    if(USE_GRAPHICS MATCHES "^SDL*")
        set(USE_ACCESSIBILITY_GENERIC TRUE)
        mark_as_advanced(USE_ACCESSIBILITY_GENERIC)
    endif(USE_GRAPHICS MATCHES "^SDL*")

    if(USE_GRAPHICS STREQUAL "MORPHOS")
       set(USE_ACCESSIBILITY_GENERIC TRUE)
       mark_as_advanced(USE_ACCESSIBILITY_GENERIC)
    endif(USE_GRAPHICS STREQUAL "MORPHOS")
endif(ENABLE_ACCESSIBILITY)

