if(ENABLE_SVG_ANIMATION OR ENABLE_SVG_AS_IMAGE OR ENABLE_SVG_FILTERS OR ENABLE_SVG_FONTS OR ENABLE_SVG_FOREIGN_OBJECT OR ENABLE_SVG_USE_ELEMENT)
    set(SVG_FLAGS ON)
endif(ENABLE_SVG_ANIMATION OR ENABLE_SVG_AS_IMAGE OR ENABLE_SVG_FILTERS OR ENABLE_SVG_FONTS OR ENABLE_SVG_FOREIGN_OBJECT OR ENABLE_SVG_USE_ELEMENT)
