#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "ppc-amigaos-gcc -DOPENSSL_THREADS -D_THREAD_SAFE -D_REENTRANT -DTERMIOS -DB_ENDIAN -O3 -fomit-frame-pointer -Wall"
  #define PLATFORM "BSD-generic32"
  #define DATE "Wed Jan 29 16:43:01     2014"
#endif
