#ifndef ASYNCIO_INTERFACE_DEF_H
#define ASYNCIO_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 50.8.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_ASYNCIO_H
#include <libraries/asyncio.h>
#endif

struct AsyncIOIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct AsyncIOIFace *Self);
	ULONG APICALL (*Release)(struct AsyncIOIFace *Self);
	void APICALL (*Expunge)(struct AsyncIOIFace *Self);
	struct Interface * APICALL (*Clone)(struct AsyncIOIFace *Self);
	struct AsyncFile * APICALL (*OpenAsync)(struct AsyncIOIFace *Self, STRPTR fileName, ULONG mode, LONG bufferSize);
	struct AsyncFile * APICALL (*OpenAsyncFromFH)(struct AsyncIOIFace *Self, BPTR handle, ULONG mode, LONG bufferSize);
	LONG APICALL (*CloseAsync)(struct AsyncIOIFace *Self, struct AsyncFile * file);
	LONG APICALL (*SeekAsync)(struct AsyncIOIFace *Self, struct AsyncFile * file, LONG position, LONG mode);
	LONG APICALL (*ReadAsync)(struct AsyncIOIFace *Self, struct AsyncFile * file, APTR buffer, LONG bytes);
	LONG APICALL (*WriteAsync)(struct AsyncIOIFace *Self, struct AsyncFile * file, APTR buffer, LONG bytes);
	LONG APICALL (*ReadCharAsync)(struct AsyncIOIFace *Self, struct AsyncFile * file);
	LONG APICALL (*WriteCharAsync)(struct AsyncIOIFace *Self, struct AsyncFile * file, ULONG ch);
	LONG APICALL (*ReadLineAsync)(struct AsyncIOIFace *Self, struct AsyncFile * file, STRPTR buf, LONG bytes);
	LONG APICALL (*WriteLineAsync)(struct AsyncIOIFace *Self, struct AsyncFile * file, STRPTR buf);
	STRPTR APICALL (*FGetsAsync)(struct AsyncIOIFace *Self, struct AsyncFile * file, STRPTR buf, LONG bytes);
	STRPTR APICALL (*FGetsLenAsync)(struct AsyncIOIFace *Self, struct AsyncFile * file, STRPTR buf, LONG bytes, LONG * length);
	LONG APICALL (*PeekAsync)(struct AsyncIOIFace *Self, struct AsyncFile * file, APTR buffer, LONG bytes);
};

#endif /* ASYNCIO_INTERFACE_DEF_H */
