#ifndef INLINE4_ASYNCIO_H
#define INLINE4_ASYNCIO_H

/*
** This file was machine generated by idltool 50.8.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_ASYNCIO_H
#include <libraries/asyncio.h>
#endif

/* Inline functions for Interface "main" */
#define OpenAsync(fileName, mode, bufferSize) IAsyncIO->OpenAsync(fileName, mode, bufferSize) 
#define OpenAsyncFromFH(handle, mode, bufferSize) IAsyncIO->OpenAsyncFromFH(handle, mode, bufferSize) 
#define CloseAsync(file) IAsyncIO->CloseAsync(file) 
#define SeekAsync(file, position, mode) IAsyncIO->SeekAsync(file, position, mode) 
#define ReadAsync(file, buffer, bytes) IAsyncIO->ReadAsync(file, buffer, bytes) 
#define WriteAsync(file, buffer, bytes) IAsyncIO->WriteAsync(file, buffer, bytes) 
#define ReadCharAsync(file) IAsyncIO->ReadCharAsync(file) 
#define WriteCharAsync(file, ch) IAsyncIO->WriteCharAsync(file, ch) 
#define ReadLineAsync(file, buf, bytes) IAsyncIO->ReadLineAsync(file, buf, bytes) 
#define WriteLineAsync(file, buf) IAsyncIO->WriteLineAsync(file, buf) 
#define FGetsAsync(file, buf, bytes) IAsyncIO->FGetsAsync(file, buf, bytes) 
#define FGetsLenAsync(file, buf, bytes, length) IAsyncIO->FGetsLenAsync(file, buf, bytes, length) 
#define PeekAsync(file, buffer, bytes) IAsyncIO->PeekAsync(file, buffer, bytes) 

#endif /* INLINE4_ASYNCIO_H */
