#ifndef INLINE4_CGXVIDEO_H
#define INLINE4_CGXVIDEO_H

/*
** This file was auto generated by idltool 53.6.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef INTUITION_INTUITION_H
#include <intuition/intuition.h>
#endif
#ifndef INTUITION_SCREENS_H
#include <intuition/screens.h>
#endif
#ifndef CYBERGRAPHX_CGXVIDEO_H
#include <cybergraphx/cgxvideo.h>
#endif
#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif
#include <interfaces/cgxvideo.h>

/* Inline macros for Interface "main" */
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define CreateVLayerHandleTags(...) ICgxvideo->CreateVLayerHandleTags(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define CreateVLayerHandleTags(vargs...) ICgxvideo->CreateVLayerHandleTags(## vargs) 
#endif
#define DeleteVLayerHandle(VLayerHandle) ICgxvideo->DeleteVLayerHandle((VLayerHandle)) 
#define AttachVLayerTagList(VLayerHandle, window, Tags) ICgxvideo->AttachVLayerTagList((VLayerHandle), (window), (Tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define AttachVLayerTags(VLayerHandle, ...) ICgxvideo->AttachVLayerTags((VLayerHandle), __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define AttachVLayerTags(VLayerHandle, vargs...) ICgxvideo->AttachVLayerTags(VLayerHandle, ## vargs) 
#endif
#define DetachVLayer(VLayerHandle) ICgxvideo->DetachVLayer((VLayerHandle)) 
#define GetVLayerAttr(VLayerHandle, AttrID) ICgxvideo->GetVLayerAttr((VLayerHandle), (AttrID)) 
#define LockVLayer(VLayerHandle) ICgxvideo->LockVLayer((VLayerHandle)) 
#define UnlockVLayer(VLayerHandle) ICgxvideo->UnlockVLayer((VLayerHandle)) 
#define SetVLayerAttrTagList(VLayerHandle, Tags) ICgxvideo->SetVLayerAttrTagList((VLayerHandle), (Tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define SetVLayerAttrTags(...) ICgxvideo->SetVLayerAttrTags(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define SetVLayerAttrTags(vargs...) ICgxvideo->SetVLayerAttrTags(## vargs) 
#endif
#define SwapVLayerBuffer(VLayerHandle) ICgxvideo->SwapVLayerBuffer((VLayerHandle)) 
#define WriteSPLine(VLayerHandle, buffer, x, y, w) ICgxvideo->WriteSPLine((VLayerHandle), (buffer), (x), (y), (w)) 
#define QueryVLayerAttr(screen, AttrID) ICgxvideo->QueryVLayerAttr((screen), (AttrID)) 

#endif /* INLINE4_CGXVIDEO_H */
